//
// Created by RottenBamboo on 2023/7/26.
//

#ifndef VULKANFROMSCRATCH_RBDESCRIPTORSET_H
#define VULKANFROMSCRATCH_RBDESCRIPTORSET_H


class RBDescriptorSet {

};


#endif //VULKANFROMSCRATCH_RBDESCRIPTORSET_H
